# Generated by Django 3.1.2 on 2020-11-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
