# Generated by Django 3.1.2 on 2020-11-06 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0002_contagionrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contagion',
            name='discharged_on',
        ),
    ]
