# Generated by Django 3.1.3 on 2020-11-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0003_remove_contagion_discharged_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagionrisk',
            name='shown',
            field=models.BooleanField(default=False),
        ),
    ]
