# Generated by Django 3.1.3 on 2020-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagion', '0004_auto_20201116_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagionrisk',
            name='location_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
