# Generated by Django 3.1.3 on 2020-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.CharField(max_length=2000),
        ),
    ]
