# Generated by Django 3.1.4 on 2020-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20201210_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_checkins',
            field=models.IntegerField(default=0),
        ),
    ]
