# Generated by Django 3.1.2 on 2020-11-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='entrance_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registry',
            name='exit_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
