# Generated by Django 3.1.3 on 2020-11-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20201106_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='entrance_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='exit_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
