# Generated by Django 3.1.3 on 2020-11-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20201112_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
