# Generated by Django 3.1.2 on 2020-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
        migrations.AddField(
            model_name='user',
            name='last_risk_update',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
