# Generated by Django 3.1.3 on 2020-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201105_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Contagion Risk', 'Contagion Risk'), ('COVID Positive', 'COVID Positive')], default='Healthy', max_length=200),
        ),
    ]
